import 'package:get/get.dart';

class Languages extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'email_hint': 'Enter Email',
          'password_hint': 'Enter Password',
          'internet_exception':
              'unable to show results, please check your internet connection',
          'general_exception':
              'we are unable to process your request, please try again',
          'welcome_back': 'Welcome Back User',
          'login': 'Login',
          'register': 'Registration',
          'mobile_hint': 'Enter Mobile',
          'survey_profile': 'Survey Profile',
          "vegetable": "Vegetables",
          'select_options': "Select Option",
          'driver': 'Drivers',
          'farmer': 'Farmers',
          'life_of_vegetable': 'Life Of Vegetable',
          "vegetable_season": 'Vegetable Season',
          'select_validity': "Select Validity",
          'select_form': 'Select From List',
          'select_to': 'Select',
          'add_photos': 'Add Photos',
          'cold_storage_required': "Cold Storage Required",
          "yes": "Yes",
          "no": "No",
          "jan": 'JAN',
          "feb": 'FEB',
          "mar": 'MAR',
          "apr": 'APR',
          "may": 'MAY',
          "jun": 'JUN',
          "july": 'JULY',
          "aug": 'AUG',
          "sep": 'SEP',
          "oct": 'OCT',
          "nov": 'NOV',
          "dec": 'DEC',
          "shortage": 'Shortage',
          "bulk": 'Bulk Available',
          "demand": 'On Demand',
          "avail": 'Not Available',
          "days": 'Days',
          "weeks": 'Weeks',
          "months": 'Months',
          "wholesaler": 'Wholesaler',
          "retailer": 'Retailer',
          "seller": 'Small Seller',
          "presence_in_market": "Presence in Market",
          'crop_details': 'Vegetable Details',
          'edit_crop_details': "Edit Vegetable Details",
          'crop_name': 'Vegetable Name',
          'crop_source': 'Vegetable Source Place',
          'driver_details': 'Driver Details',
          'driver_name': 'Driver Name',
          'vehicle_number': 'Vehicle Number',
          'crop_qty': 'Vegetable Quantity',
          'round_trip': 'Round Trip',
          'driver_area': "Driver's Area",
          'owner_name': 'Vehicle Owner Name',
          'driver_contact': 'Driver Contact',
          'driver_alternate_number': 'Driver Alternate No.',
          'farmer_details': 'Farmer Details',
          'farmer_name': 'Farmer Name',
          'farmer_contact': 'Farmer Contact',
          'farmer_alternate_number': "Farmer Alternate No.",
          'farmer_area': 'Farmer Area',
          'crop_carrying_qty': 'Vegetable Carrying Qty (kg)',
          'crop_qty_produce': 'Vegetable Produce Qty (kg)',
          'mandi_distance': 'Mandi Distance',
          'transport_name': 'Transport Name',
          'farmer_visit': 'Farmer Visit',
          'selling_area': 'Selling Area',
          'mandi_name': 'Mandi Name',
          'crop_variety': 'Vegetable Variety',
          'commission_amount': 'Commission',
          "vendor_details": 'Vendor Detail',
          'vendor_name': 'Vendor Name',
          'vendor_number': 'Vendor Number',
          'vendor_alternate_number': 'Vendor Alternate No.',
          'vendor_address': 'Vendor Address',
          'shop_address': "Shop Address",
          'mandi_priority': 'Mandi Priority',
          'mandi_visit': 'Mandi Visit',
          'vegetable_type': 'Vendor Type',
          'vegetable_variety': 'Vegetable Variety',
          'select_type': 'Select Type',
          "vendor_age": "Vendor Age",
          'select_age': "Select Age",
          "vendor": "Vendor",
          "vendor_type": "Vendor Type"
        },
        'hi_IN': {
          "vendor": "विक्रेता",
          "vendor_type": "विक्रेता का प्रकार",
          "vendor_details": "विक्रेता विवरण",
          "vendor_age": "विक्रेता आयु",
          'vendor_name': 'विक्रेता का नाम',
          'vendor_number': 'विक्रेता का नंबर',
          'vendor_alternate_number': 'विक्रेता वैकल्पिक नंबर',
          'vendor_address': 'विक्रेता पता',
          'shop_address': 'दुकान पता',
          'mandi_priority': 'मंडी प्राथमिकता',
          'mandi_visit': 'मंडी भ्रमण',
          'vendor_type': 'विक्रेता प्रकार',
          'vegetable_variety': 'सब्जी की विविधता',
          'select_type': 'प्रकार चुनें',
          'select_age': 'उम्र चुनें',
          "jan": 'JAN',
          "feb": 'FEB',
          "mar": 'MAR',
          "apr": 'APR',
          "may": 'MAY',
          "jun": 'JUN',
          "july": 'JULY',
          "aug": 'AUG',
          "sep": 'SEP',
          "oct": 'OCT',
          "nov": 'NOV',
          "dec": 'DEC',
          "shortage": 'Shortage',
          "bulk": 'Bulk Available',
          "demand": 'On Demand',
          "avail": 'Not Available',
          "days": 'Days',
          "weeks": 'Weeks',
          "months": 'Months',
          "wholesaler": 'Wholesaler',
          "retailer": 'Retailer',
          "seller": 'Small Seller',
          'email_hint': 'अपना ईमेल दर्ज करें',
          'password_hint': 'पासवर्ड दर्ज करें',
          'internet_exception':
              'परिणाम दिखाने में असमर्थ, कृपया अपना इंटरनेट कनेक्शन जांचें',
          'general_exception':
              'हम आपके अनुरोध पर कार्रवाई करने में असमर्थ हैं, कृपया पुनः प्रयास करें',
          'welcome_back': 'उपयोगकर्ता का पुनः स्वागत है',
          'login': 'लॉग इन करें',
          'register': 'पंजीकरण',
          'mobile_hint': 'मोबाइल दर्ज करें',
          'select_options': "विकल्प चुनें",
          'survey_profile': 'सर्वेक्षण प्रोफ़ाइल',
          "vegetable": "सब्ज़ी",
          'driver': 'ड्राइवर',
          'farmer': 'किसान',
          'crop_details': 'फसल विवरण',
          'edit_crop_details': "सब्जी विवरण संपादित करें",
          'life_of_vegetable': 'सब्जी की खराब होने की वैधता',
          "vegetable_season": 'सब्जी का मौसम',
          'select_validity': 'वैधता चुनें',
          'select_form': 'कब सें',
          'select_to': 'कब तकं',
          'cold_storage_required': 'कोल्ड स्टोरेज की आवश्यकता',
          "yes": "Yes",
          "no": "No",
          "add_photos": "तस्वीरें जोडो",
          "presence_in_market": 'बाज़ार में उपस्थिति',
          'crop_name': 'फसल का नाम',
          'crop_source': 'फसल स्रोत स्थान',
          'driver_details': 'ड्राइवर का विवरण',
          'driver_name': 'चालक का नाम',
          'vehicle_number': 'गाडी नंबर',
          'crop_qty': 'फसल की मात्रा',
          'round_trip': 'राउंड ट्रिप',
          'driver_area': "चालक का पता",
          'owner_name': 'वाहन स्वामी का नाम',
          'driver_contact': 'ड्राइवर संपर्क नंबर',
          'driver_alternate_number': 'ड्राइवर वैकल्पिक नंबर',
          'farmer_details': 'किसान विवरण',
          'farmer_name': 'किसान का नाम',
          'farmer_contact': 'किसान संपर्क नंबर',
          'farmer_alternate_number': 'किसान वैकल्पिक नंबर',
          'farmer_area': 'किसान का पता',
          'crop_carrying_qty': 'मंडी लायी गई फसल की मात्रा (kg)',
          'crop_qty_produce': 'उपज की गई गई फसल की मात्रा(kg)',
          'mandi_distance': 'मंडी की दूरी',
          'transport_name': 'परिवहन नाम',
          'farmer_visit': 'किसान दौरा',
          'selling_area': 'विक्रय क्षेत्र',
          'mandi_name': 'मंडी नाम',
          'crop_variety': 'फसल प्रकार',
          'commission_amount': 'कमीशन राशि',
        }
      };
}
